function [wrapped_state] = EKF_wrap_state(x)
% Takes in the state vector and wraps all the angle variables to pi.

wrapped_state=[x(1);...
               x(2);...
               wrapToPi(x(3));...
               x(4);...
               x(5);...
               wrapToPi(x(6))];
end

